In [2]:
import pandas as pd
import numpy as np

In [3]:
import os

print(os.getcwd())

C:\Users\rajbi\OneDrive\Desktop\ecommerce-sales-analysis\notebook

In [4]:
os.listdir()

['.ipynb_checkpoints', 'data_cleaning.ipynb']

In [6]:
df = pd.read_csv("../customers.csv")

In [6]:
df.head()

   customer_id signup_date state acquisition_channel
0            1  2024-09-13    CO      organic_search
1            2  2025-10-21    IL         paid_search
2            3  2025-01-17    AZ            referral
3            4  2024-06-23    FL         paid_social
4            5  2025-04-08    IL         paid_social

In [7]:
df.shape

(3600, 4)

In [8]:
df.columns

Index(['customer_id', 'signup_date', 'state', 'acquisition_channel'], dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          3600 non-null   int64
 1   signup_date          3600 non-null   str
 2   state                3600 non-null   str
 3   acquisition_channel  3600 non-null   str
dtypes: int64(1), str(3)
memory usage: 112.6 KB

In [10]:
df.describe()

       customer_id
count  3600.000000
mean   1800.500000
std    1039.374812
min       1.000000
25%     900.750000
50%    1800.500000
75%    2700.250000
max    3600.000000

In [11]:
df.describe(include="object")

C:\Users\rajbi\AppData\Local\Temp\ipykernel_25492\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

       signup_date state acquisition_channel
count         3600  3600                3600
unique         811    35                   6
top     2025-10-29    CA      organic_search
freq            17   451                1230

In [12]:
df.isnull().sum()

customer_id            0
signup_date            0
state                  0
acquisition_channel    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [15]:
df.columns

Index(['customer_id', 'signup_date', 'state', 'acquisition_channel'], dtype='str')

In [19]:
df.to_csv(
    "../cleaned/customers_cleaned.csv",
    index=False
)